<?php

/**
 * Language
 *
 * PHP version 8.1
 *
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SimplePay API v2
 *
 * This is a SimplePay API v2 documentation.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: hello@conedevelopment.com
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Cone\SimplePay\Model;

/**
 * Language Class Doc Comment
 *
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
enum Language: string
{
    case AR = 'AR';

    case BG = 'BG';

    case CS = 'CS';

    case DE = 'DE';

    case EN = 'EN';

    case ES = 'ES';

    case FR = 'FR';

    case IT = 'IT';

    case HR = 'HR';

    case HU = 'HU';

    case PL = 'PL';

    case RO = 'RO';

    case RU = 'RU';

    case SK = 'SK';

    case TR = 'TR';

    case ZH = 'ZH';
}
