<?php

/**
 * Status
 *
 * PHP version 8.1
 *
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SimplePay API v2
 *
 * This is a SimplePay API v2 documentation.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: hello@conedevelopment.com
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Cone\SimplePay\Model;

/**
 * Status Class Doc Comment
 *
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
enum Status: string
{
    case INIT = 'INIT';

    case TIMEOUT = 'TIMEOUT';

    case CANCELLED = 'CANCELLED';

    case NOTAUTHORIZED = 'NOTAUTHORIZED';

    case INPAYMENT = 'INPAYMENT';

    case INFRAUD = 'INFRAUD';

    case AUTHORIZED = 'AUTHORIZED';

    case REVERSED = 'REVERSED';

    case FINISHED = 'FINISHED';
}
