<?php

/**
 * AuthMethodTest
 *
 * PHP version 8.1
 *
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SimplePay API v2
 *
 * This is a SimplePay API v2 documentation.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: hello@conedevelopment.com
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Cone\SimplePay\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * AuthMethodTest Class Doc Comment
 *
 * @description AuthMethod
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class AuthMethodTest extends TestCase
{
    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "AuthMethod"
     */
    public function testAuthMethod()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
